admin:
    pattern: /admin/
    defaults: { _controller: liip_hackday.controller:indexAction }

admin_create:
    pattern: /admin/create
    defaults: { _controller: liip_hackday.controller:createAction }
